name: ci
on: pull_request
jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=3m
  go-test:
    strategy:
      matrix:
        go-version: [1.22.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: go tests
        run: go test -v -covermode=count -json ./... > test.json
      - name: annotate go tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.5.1
        with:
          test-results: test.json
  test:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      # Add any environment variables needed to run baton-bitbucket-datacenter
      BATON_DEPLOYMENT_API_KEY: ${{ secrets.BATON_DEPLOYMENT_API_KEY }}
      BATON_DEPLOYMENT_ENDPOINT: ${{ secrets.BATON_DEPLOYMENT_ENDPOINT }}
      BATON_ORGANIZATION_ID: ${{ secrets.BATON_ORGANIZATION_ID }}
      BATON_API_KEY: ${{ secrets.BATON_API_KEY }}
      # The following parameters are passed to grant/revoke commands
      CONNECTOR_GRANT: 'roleMapping:mapping7:member:deploymentUser:jacknich'
      CONNECTOR_ENTITLEMENT: 'roleMapping:mapping7:member'
      CONNECTOR_PRINCIPAL_TYPE: 'deploymentUser'
      CONNECTOR_PRINCIPAL: 'jacknich'
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install baton
        run: ./scripts/get-baton.sh && mv baton /usr/local/bin
      - name: Build baton-elastic
        run: go build ./cmd/baton-elastic
      - name: Run baton-elastic
        run: ./baton-elastic
      - name: Revoke grants
        run: |
          ./baton-elastic
          ./baton-elastic --revoke-grant ${{ env.CONNECTOR_GRANT }}
      - name: Grant entitlement
        run: | 
          ./baton-elastic 
          ./baton-elastic --grant-entitlement ${{ env.CONNECTOR_ENTITLEMENT }} --grant-principal-type ${{ env.CONNECTOR_PRINCIPAL_TYPE }} --grant-principal ${{ env.CONNECTOR_PRINCIPAL }}  --provisioning
